name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create zip archive
      run: |
        zip -r TheOwlHouseMod.zip "assets/ *.lua README.md LICENCE"

    - name: Upload Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: TheOwlHouseMod.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
